name: pgp5
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - pip:
    - ccxt==1.72.1
    - matplotlib==3.0.3
    - numpy==1.18.5
    - pandas==0.20.0
    - scipy==1.4.1
    - pip==20.3.4
    - tensorflow-gpu==1.15
    - git+https://github.com/MihaMarkic/tflearn.git@fix/is_sequence_missing
